### PR TITLE
Dual Interface

### PR DESCRIPTION
**Pull request by Yefancy**
Sorry for my sloppy in my previous work. However, this two days I reimplemented `ME Dual Interface` according to the problem mentioned earlier. It mainly includes the following contents:

- An interface containing the complete function of the `ME Interface` and the `ME Fluid Interface` is implemented.
- Buttons were added to switch the GUIs.
- A slight hack of the interface terminal to show `ME Dual Interface` .
- Fixed issues mentioned and modified textures (not pretty, but acceptable).

My own test runs well, but there may be some unknown bugs. This PR is a little hurry. Because ae2fc is updated frequently on the core framework recently, and I hope to avoid some conflicts.

### CODE REVIEW

**Comment by Yefancy** [comment]
Still there?

**Comment by phantamanta44** [comment]
sorry, been extremely busy with schoolwork. i'll take a look at this when i have a chance to, but that might be a while

**Comment by Yefancy** [comment]
yes, rl is more important, best wishes for you then.

**Comment by phantamanta44** [comment]
wow, that's a lot of work. hopefully, i'll be able to go over this by the end of the week...

**Comment by Yefancy** [comment]
It looks like you're still busy.

**Comment by phantamanta44** [comment]
as it would happen, my thanksgiving break just started today, so i'll finally be able to look at this

**Comment by phantamanta44** [comment]
alright, this is broadly very good work, but there are a few small things I would want implemented differently. I'm thinking about just merging and making the changes myself; is this an okay resolution with you?

**Comment by Yefancy** [comment]
Of course. After all, it's your stuff, and I only expect such features. Have a nice break.

**Comment by phantamanta44** [comment]
cool! thanks for all your hard work. if you have a curseforge account, I can add you as a contributor there, if you'd like

**Comment by Yefancy** [comment]
I have no curse forge account. It doesn't matter, and I'm happy to contribute to this mod.

**Pull request merged**
